eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
      fetchRegistry=true :
spring:
  application:
    name: customerservice
  cloud:
    discovery:
      enabled: true
  data:
    mongobd:
      database: customerDB
      port: 27017
server:
  port: 8075
management :
  endpoints :
    web :
      exposure :
        include : "*"



