package com.demo.customerservice.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;


@Data
public class Account {

    @Id
    private Integer accountId;  //will be autogenerated in DB
    private Long accountNumber; //will be autogenerated in DB

    @Enumerated(EnumType.STRING)
    private AccountType accountType;
    private Long accountBalance; //hardcoded value
    private int customerId; //passed by customerservice application
    private Boolean isAccountActive;

    public Account(Long accountNumber, AccountType accountType, Long accountBalance, int customerId,Boolean isAccountActive) {
        this.accountNumber = accountNumber;
        this.accountType = accountType;
        this.accountBalance = accountBalance;
        this.customerId = customerId;
        this.isAccountActive= isAccountActive;

    }
}
