package com.demo.accountservice.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Value;

import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;


@Entity
@Table(name="accounts")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Account {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer accountId;  //will be autogenerated in DB

   // @NotBlank(message="accountNumber cannot be blank")
    private Long accountNumber; //will be autogenerated in DB


    @Value("1000")
    private Long accountBalance; //default value
    private int customerId; //passed by customerservice application

    @Enumerated(EnumType.STRING)
    private AccountType accountType;

    @Value("true")
    private Boolean isAccountActive;


    }

