#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/account_db
#    username: root
#    password: root7039
#    driver:
#      class:
#        name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl:
#        auto: update
#  application:
#    name: accountservice
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
#    hostname: localhost
#  cloud:
#    discovery:
#      enabled: true
#server:
#  port: 8071